name: Deploy Backend to GHCR and Render

on:
  push:
    branches:
      - main

permissions:
  contents: read 

env:
  IMAGE_NAME: ghcr.io/${{ lower(github.repository) }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR (Using Repository Secret)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GHCR_PAT }} 

      - name: Build and push images
        run: |

          SHA_TAG=${{ env.IMAGE_NAME }}:${{ github.sha }}

          LATEST_TAG=${{ env.IMAGE_NAME }}:latest
          
          echo "Building image $LATEST_TAG..."
          docker build -t $SHA_TAG -t $LATEST_TAG .
          
          echo "Pushing images..."
          docker push $SHA_TAG
          docker push $LATEST_TAG