name: Deploy Backend to GHCR and Render

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/victorjimenezcanche/bck_bt_ordinario/flask-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GHCR
      run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Push Docker image
      run: docker push $IMAGE_NAME:latest
